name: Trigger Deploy

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger deploy workflow
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: zawert879/test-deploy
        event-type: trigger-deploy
